services:
    nodejs:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "3000:3000"

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nodejs/public:/usr/share/nginx/html