services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nodejs/public:/usr/share/nginx/html

  postgresql:
    container_name: postgresql
    image: postgres:latest
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    restart: always


