services:
  streaming-audio:
    image:
    ports:
      - "8080:80"

  postgres-db:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    restart: always  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nodejs/public:/usr/share/nginx/html
